

data:
  batch_size: 28
  max_batch_size: 28
  num_workers: 4
  prefetch_factor: 100
  csv_path: /home/hm638/project_pi_sk2433/hm638/ImmunoFoundation/data/metadata.csv
  structure:
    adj: false
    graph_type: knn
    k: 5

model:
  sequence:
    freeze_esm: true
    aggregate: false
    rep_layer: 33
    esm_variant: esm2_t33_650M_UR50D
    out_dim: 32
  structure:
    out_dim: 32
    n_heads: 8
    dim_ffn: 256
    n_layers: 4
  bio_chem:
    n_bio_prop: 93 #DO NOT CHANGE THIS
    hidden_dim: 64
    out_dim: 32
    n_layers: 4


sequence:
  use_esm: True
  model_name: esm2_t6_8M_UR50D   # small default -- adjust as needed
  out_dim: 256                   # embedding dimension returned by SequenceModel
  freeze_esm: True               # True -> don't fine-tune ESM weights
  vocab: 'ACDEFGHIKLMNPQRSTVWYJ' # optional; last char is padding char
  
optimizer:
  lr: 1e-4
  weight_decay: 1e-6

experiment:
  debug: False
  num_devices: 1

  wandb:
    name: null
    project: immunofoundation
    save_code: false
    tags: []
    mode: "online" # can also save to `offline`

  optimizer:
    lr: 0.0001

  trainer:
    min_epochs: 1
    max_epochs: 200
    accelerator: gpu
    log_every_n_steps: 1
    deterministic: False
    strategy: ddp #ddp
    check_val_every_n_epoch: 20
    accumulate_grad_batches: 4

  checkpointer:
    dirpath: ckpt/${experiment.wandb.project}/${experiment.wandb.name}/
    save_last: True
    save_top_k: 3
    monitor: train/loss
    mode: min
    every_n_epochs: 40