
data:
  batch_size: 32
  max_batch_size: 32
  num_workers: 8
  train_size: 0.8
  mono: false
  prefetch_factor: 4
  csv_path: data/dimer_filtered.csv
  mask:
    mask_rate: 0.5
    max_distance: 8
    max_neighbors: 12
  structure:
    adj: true
    graph_type: knn
    k: 15
    
model:
  sequence:
    model_type: esm
    freeze_esm: true
    aggregate: false
    esm_dim: 1280
    rep_layer: 33
    esm_variant: esm2_t33_650M_UR50D
    out_dim: 32
    n_heads: 8
    dim_ffn: 256
    n_layers: 10
  structure:
    model_type: transformer
    out_dim: 32
    n_heads: 8
    dim_ffn: 256
    n_layers: 4 

optimizer:
  lr: 1e-4
  weight_decay: 1e-6

experiment:
  debug: False
  num_devices: 4

  wandb:
    name: "afdb_phase_2_no_checkpoint"
    project: immunofoundation
    save_code: false
    tags: []
    mode: "online" # can also save to `offline`

  optimizer:
    lr: 0.0001

  trainer:
    min_epochs: 1
    max_epochs: 200
    accelerator: gpu
    log_every_n_steps: 1
    deterministic: False
    strategy: ddp
    check_val_every_n_epoch: 2
    accumulate_grad_batches: 4

  checkpointer:
    dirpath: ckpt/${experiment.wandb.project}/${experiment.wandb.name}
    save_last: True
    save_top_k: 3
    monitor: val/total_loss
    mode: min
    every_n_epochs: 2
